### ISSUE TITLE
cant download when sync

### ISSUE THREAD

**Issue by hideandseekstheorder** [YuriCosta/WhatsApp-GD-Extractor-Multithread#17]
C:\Users\muham\OneDrive\Desktop\WhatsApp-GD-Extractor-Multithread-master>python3 WhatsAppGDExtract.py sync
Backup clients/wa/backups/6283806508787 (1GiB):
Progress:   0.806% VID-20201206-WA0002.mp4                                     Traceback (most recent call last):
  File "C:\Users\muham\OneDrive\Desktop\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 230, in <module>
    main(sys.argv)
  File "C:\Users\muham\OneDrive\Desktop\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 227, in main
    wa_backup.fetch_all(backup, cksums)
  File "C:\Users\muham\OneDrive\Desktop\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 126, in fetch_all
    for name, size, md5Hash in downloads:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 870, in next
    raise value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\muham\OneDrive\Desktop\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 123, in <lambda>
    lambda file: self.fetch(file),
  File "C:\Users\muham\OneDrive\Desktop\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 113, in fetch
    self.get(file["name"].replace("%", "%25"), {"alt": "media"}, stream=True)
  File "C:\Users\muham\OneDrive\Desktop\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 81, in get
    response.raise_for_status()
  File "C:\Users\muham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://backup.googleapis.com/v1/clients/wa/backups/6283806508787/files/Media/WhatsApp%20Documents/Private/?alt=media#Konsep%20Design%20Logo%20HIMTI%20.pdf

**Comment by LukasSpukas** [comment]
Had the same problem. Commenting out line 81 of the python script fixed it for me but now it probably can not guarantee to download all files.

**Comment by cexaro** [comment]
had the same problem, i try skip this file but i not have lucky..... im sad

**Comment by Alcazer** [comment]
Can you download the latest version and try again?

**Comment by YuriCosta** [comment]
Anyone else has this problem even with python3?

**Comment by cexaro** [comment]
My problem was resolve thanks a lot!!

**Comment by fares4ever2021** [comment]
(root💀kali)-[~/WhatsApp-GD-Extractor-Multithread]
└─# python3 WhatsAppGDExtract.py sync
Traceback (most recent call last):
  File "/root/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 234, in <module>
    main(sys.argv)
  File "/root/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 221, in main
    for backup in backups:
  File "/root/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 95, in list_path
    for item in page[last_component]:
KeyError: 'backups'

**Comment by YuriCosta** [comment]
> (root💀kali)-[~/WhatsApp-GD-Extractor-Multithread]
> └─# python3 WhatsAppGDExtract.py sync
> Traceback (most recent call last):
> File "/root/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 234, in
> main(sys.argv)
> File "/root/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 221, in main
> for backup in backups:
> File "/root/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 95, in list_path
> for item in page[last_component]:
> KeyError: 'backups'

Maybe the backup is corrupt.
