### ISSUE TITLE
cant download when sync

### ISSUE THREAD

**Issue by hideandseekstheorder** [YuriCosta/WhatsApp-GD-Extractor-Multithread#18]
on termux

# python3 WhatsAppGDExtract.py sync
Backup clients/wa/backups/6283806508787 (1GiB):            Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink       ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)
                                                           During handling of the above exception, another exception occurred:                                                   
Traceback (most recent call last):                           File "/data/data/com.termux/files/home/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 230, in <module>
    main(sys.argv)                                           File "/data/data/com.termux/files/home/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 227, in main       wa_backup.fetch_all(backup, cksums)
  File "/data/data/com.termux/files/home/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 121, in fetch_all                                                             with ThreadPool(10) as pool:                             File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/pool.py", line 927, in __init__                     Pool.__init__(self, processes, initializer, initargs)    File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/pool.py", line 196, in __init__                     self._change_notifier = self._ctx.SimpleQueue()          File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 113, in SimpleQueue               return SimpleQueue(ctx=self.get_context())               File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/queues.py", line 342, in __init__                   self._rlock = ctx.Lock()                                 File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 67, in Lock                       from .synchronize import Lock                            File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 30, in <module>               raise ImportError("This platform lacks a functioning sem_open" +                                                  ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.             #

**Comment by Alcazer** [comment]
Its a Python problem with your system configuration, you can try clean install

**Comment by YuriCosta** [comment]
Try with python3
