### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by damasusbagus** [YuriCosta/WhatsApp-GD-Extractor-Multithread#25]
```
Traceback (most recent call last):
  File "WhatsAppGDExtract.py", line 230, in <module>
    main(sys.argv)
  File "WhatsAppGDExtract.py", line 206, in main
    for backup in backups:
  File "WhatsAppGDExtract.py", line 94, in list_path
    page = self.get_page(path, page_token)
  File "WhatsAppGDExtract.py", line 85, in get_page
    return self.get(
  File "WhatsAppGDExtract.py", line 77, in get
    headers={"Authorization": "Bearer {}".format(self.auth["Auth"])},
KeyError: 'Auth'
```

**Comment by Alcazer** [comment]
Please fill settings.cfg correctly and try again

**Comment by Alcazer** [comment]
@damasusbagus is it resolved?
