### ISSUE TITLE
One Google Account with two whatsapp backup failure

### ISSUE THREAD

**Issue by TehBotolSosro** [YuriCosta/WhatsApp-GD-Extractor-Multithread#26]
The Script worked great thanks,
But seem there is an issue if the google account have two whatsapp backup (two phone number)
it will only downloaded the first phone number

and it cause error for every command (sync/info/list)

```
Sync Result 
Progress: 100.000% PTT-20210111-WA0015.opus
234 files (45MiB)
Traceback (most recent call last):
  File "C:\twowha\WhatsAppGDExtract.py", line 230, in <module>
    main(sys.argv)
  File "C:\twowha\WhatsAppGDExtract.py", line 224, in main
    human_size(int(backup["sizeBytes"])),
KeyError: 'sizeBytes'
```

```
Info Result

Traceback (most recent call last):
File "C:\twowha\WhatsAppGDExtract.py", line 230, in
main(sys.argv)
File "C:\twowha\WhatsAppGDExtract.py", line 207, in main
print(backup_info(backup))
File "C:\twowha\WhatsAppGDExtract.py", line 179, in backup_info
metadata = json.loads(backup["metadata"])
KeyError: 'metadata'
```

**Comment by Alcazer** [comment]
Can you download the latest version and try again?

**Comment by Alcazer** [comment]
@TehBotolSosro is it resolved?

**Comment by TehBotolSosro** [comment]
sorry for the late reply,

i think the issue with the second phone number is because the backup is incomplete/ corrupted and causing the error

i tried the new version it still give me the error 

Do you want xxxx1? [y/n] : y
Backup Size:1GiB Upload Time: 2021-11-06T22:25:00.585291Z
Progress: 100.000% PTT-202111206-WA0199.opus
6672 files (1GiB)

Do you want xxxx2? [y/n] : y
Traceback (most recent call last):
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 248, in main
    print("Backup Size:{} Upload Time: {}".format(human_size(int(backup["sizeBytes"])), backup["updateTime"]))
KeyError: 'sizeBytes'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 260, in <module>
    main(sys.argv)
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 253, in main
    human_size(int(backup["sizeBytes"])),
KeyError: 'sizeBytes'
```

**Comment by Alcazer** [comment]
As you said the second account backup is incomplete/ corrupted.
Can you try again with info and list commands?

**Comment by TehBotolSosro** [comment]
the command list on the second number give 

```
Do you want xxx2? [y/n] : y
Traceback (most recent call last):
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 260, in <module>
    main(sys.argv)
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 226, in main
    for file in wa_backup.backup_files(backup):
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 105, in list_path
    for item in page[last_component]:
KeyError: 'files'
```

for info even with the first number it already give an error

```
Do you want xxx1? [y/n] : y
Traceback (most recent call last):
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 260, in <module>
    main(sys.argv)
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 217, in main
    backup_info(backup)
  File "C:\Users\HDMF\Downloads\Compressed\whapa-master_3\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 192, in backup_info
    print("Backup {} Size:({}) Upload Time:{}".format(backup["name"].split("/")[-1], metadata["backupSize"]), backup["updateTime"])
IndexError: Replacement index 2 out of range for positional args tuple
```

**Comment by Alcazer** [comment]
The second account backup is indeed corrupt. 

The only solution for you
---
Go to https://drive.google.com/drive/backups and delete it. Then backup again from whatsapp app.

**Comment by Alcazer** [comment]
@TehBotolSosro is there any news?
