### ISSUE TITLE
Cant download sync

### ISSUE THREAD

**Issue by studiophoyo** [YuriCosta/WhatsApp-GD-Extractor-Multithread#27]
Backup clients/wa/backups/XXXXXX (4GiB):
Progress:  11.846% msgstore.db.crypt14                                         Traceback (most recent call last):
  File "\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 230, in <module>
    main(sys.argv)
  File "\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 227, in main
    wa_backup.fetch_all(backup, cksums)
  File "\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 126, in fetch_all
    for name, size, md5Hash in downloads:
  File "\Python\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
  File "\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 123, in <lambda>
    lambda file: self.fetch(file),
  File "\WhatsAppGDExtract.py", line 111, in fetch
    download_file(
  File "\WhatsAppGDExtract.py", line 53, in download_file
    with open(file, "bw") as dest:
FileNotFoundError: [Errno 2] No such file or directory: 'XXXXXXXXX\\files\\Media\\WhatsApp Animated Gifs\\Sent\\VID-20201110-WA0049.mp4'

**Comment by rodrigopar99** [comment]
This just happened to me :(

**Comment by Alcazer** [comment]
Can you download the latest version, backup google drive and try again?

**Comment by Alcazer** [comment]
@studiophoyo and @rodrigopar99 is it resolved?
