### ISSUE TITLE
"Corrupted/Incomplete backup" alert and script stops at 0.002% progress when syncing (#33)

### ISSUE THREAD

**Issue by sebastianberrio** [YuriCosta/WhatsApp-GD-Extractor-Multithread#34]
I am using the fix #33 , and when I am going to sync, I get the following message:

Backup clients/wa/backups/xxxxxxxxxxx (3GiB):
Progress:   0.002% statusranking.db.crypt1                                     Corrupted/Incomplete Backup!

Also, when I use "list", it shows the name of 10 files, but then I get this:

Traceback (most recent call last):
  File "C:\Users\XXXXX\Desktop\WhatsApp-GD-Extractor-Multithread-master\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 242, in <module>
    main(sys.argv)
  File "C:\Users\XXXXX\Desktop\WhatsApp-GD-Extractor-Multithread-master\WhatsApp-GD-Extractor-Multithread-master\WhatsAppGDExtract.py", line 224, in main
    total_size += int(file["sizeBytes"])
KeyError: 'sizeBytes'

**Comment by Alcazer** [comment]
Please try again

**Comment by sebastianberrio** [comment]
Thank you. It works now for me
