### ISSUE TITLE
Crash after selecting number

### ISSUE THREAD

**Issue by Attivik** [YuriCosta/WhatsApp-GD-Extractor-Multithread#37]
This happens when running the program with correct settings:

```
$ python3 WhatsAppGDExtract.py info

Do you want [number redacted]? [y/n] : y
Traceback (most recent call last):
  File "/home/attivik/WhatsApp-GD-Extractor-Multithread-master/WhatsAppGDExtract.py", line 260, in <module>
    main(sys.argv)
  File "/home/attivik/WhatsApp-GD-Extractor-Multithread-master/WhatsAppGDExtract.py", line 217, in main
    backup_info(backup)
  File "/home/attivik/WhatsApp-GD-Extractor-Multithread-master/WhatsAppGDExtract.py", line 192, in backup_info
    print("Backup {} Size:({}) Upload Time:{}".format(backup["name"], metadata["backupSize"]), backup["updateTime"])
IndexError: Replacement index 2 out of range for positional args tuple
```

The problem is with this line: https://github.com/YuriCosta/WhatsApp-GD-Extractor-Multithread/commit/9c351173cb3800a4f46053f9882a6cfe59f1eef1#diff-0e235c4a6385276b9f1b162db7766b11e913e82ea405f7ece6c1286643536badR192

After changing to:

```
print("Backup {} Size:({}) Upload Time:{}".format(backup["name"].split("/")[-1], metadata["backupSize"], backup["updateTime"]))
```

It goes fine, I just moved the ")" of format.

**Comment by Attivik** [comment]
Fixed in pull request #35, please check and merge
